MeetMap/MeetMap/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainapp.urls')),
]

MeetMap/mainapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainapp'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^createprofile/', views.createprofile, name='createprofile'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^map/', views.map, name='map'),
    url(r'^get_events/', views.get_events, name='get_events'),
    url(r'^create_event/', views.create_event, name='createevent'),
    url(r'^get_user_details/', views.get_user_details, name='getuserdetails'),
    url(r'^going_to_event/', views.going_to_event, name='goingtoevent'),
    url(r'^not_going_to_event/', views.not_going_to_event, name='notgoingtoevent'),
    url(r'^delete_event/', views.delete_event, name='deleteevent'),
    url(r'^mymeets/', views.mymeets, name='mymeets'),
    url(r'^get_profile/', views.get_profile, name='get_profile'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^', views.login, name='login'),
]

MeetMap/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User


class InterestManager(models.Manager):
    def get_by_natural_key(self, interest_name):
        return self.get(interest_name=interest_name)


class Interest(models.Model):
    objects = InterestManager()

    interest_name = models.CharField(max_length=100)

    def natural_key(self):
        return(self.interest_name)

    def __str__(self):
        return self.interest_name


class UserProfileManager(models.Manager):
    def get_by_natural_key(self, username):
        return self.get(username=username)


class UserProfile(models.Model):
    objects = UserProfileManager()

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=100,default="")
    display_picture = models.ImageField(null=True,upload_to = 'profile_pic_folder/')
    description = models.CharField(max_length=500,default="",null=True)
    interests = models.ManyToManyField('Interest', blank=True)
    whitelist = models.ManyToManyField('self', blank=True)
    blacklist = models.ManyToManyField('self', blank=True)
    events = models.ManyToManyField('Event', blank=True)

    def natural_key(self):
        return(self.username)

    def __str__(self):
        return self.user.username


class LocationManager(models.Manager):
    def get_by_natural_key(self, latitude, longitude, street_number, street_name, suburb,
                           city, zipcode):
        return self.get(latitude = latitude,
                        longitude = longitude,
                        street_number = street_number,
                        street_name = street_name,
                        suburb = suburb,
                        city = city,
                        zipcode = zipcode)


class Location(models.Model):
    objects = LocationManager()

    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    street_number = models.CharField(max_length=100)
    street_name = models.CharField(max_length=100)
    suburb = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    zipcode = models.IntegerField()

    def natural_key(self):
        return(self.latitude, self.longitude, self.street_number, self.street_name, self.suburb,
               self.city, self.zipcode)


    def __str__(self):
        return self.street_number + " " + \
               self.street_name + ", " + \
               self.suburb + ", " + \
               self.city + " " + \
               str(self.zipcode)

class Event(models.Model):
    name = models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    from_time = models.DateTimeField()
    to_time = models.DateTimeField()
    description = models.CharField(max_length=500,default="")
    picture = models.ImageField(null=True,upload_to = 'event_pic_folder/', blank=True)
    is_private = models.BooleanField(default=False)
    interests = models.ManyToManyField(Interest)
    creator = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + " | Creator: " + self.creator.user.username

MeetMap/mainapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.postgres.forms import SimpleArrayField

from .models import Event, UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(label='Enter Username: ')
    password = forms.CharField(label='Enter Password: ')

class RegisterForm(forms.Form):
    username = forms.CharField(label='Enter a Username: ')
    password1 = forms.CharField(label='Create a Password: ')
    password2 = forms.CharField(label='Confirm Password: ')
    email = forms.CharField(label='Enter your email address: ')

class CreateEventForm(forms.ModelForm):
    street_number = forms.IntegerField(label='Street Number')
    street_name = forms.CharField(label='Street Name')
    suburb = forms.CharField(label='Suburb')
    city = forms.CharField(label='City')
    zipcode = forms.IntegerField(label='ZipCode')
    latitude = forms.FloatField(label='Latitude')
    longitude = forms.FloatField(label='Longitude')

    class Meta:
        model = Event
        exclude = ['creator','location']
        labels = {
            'name' : 'What do you call the event ?',
            'from_time' : 'When does the event start ?',
            'to_time' : 'When does the event end ?',
            'description' : 'Tell us a bit about your event',
            'picture' : 'Show a picture about your event',
            'is_private' : 'Is your event private ?',
            'interests' : 'Tag your event for others to find'
        }
        initial = {
            'is_private' : False
        }

class GoingToEventForm(forms.Form):
    event_id = forms.IntegerField()

class NotGoingToEventForm(forms.Form):
    event_id = forms.IntegerField()

class DeleteEventForm(forms.Form):
    event_id = forms.IntegerField()

class GetEventsForm(forms.Form):
    interests = SimpleArrayField(forms.CharField())

class MyMeetsForm(forms.Form):
    action_type = forms.CharField()
    event_id = forms.IntegerField()

class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['display_picture','description','interests']
        labels = {
            'display_picture':'Pick a profile picture !',
            'description':'Tell us a bit about yourself',
            'interests':'What are you interested in ?'
        }

MeetMap/mainapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.http import Http404
from django.template import loader
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.core import serializers

from .models import UserProfile, Location, Event , Interest

from .forms import LoginForm, RegisterForm, CreateEventForm, GoingToEventForm
from .forms import NotGoingToEventForm, DeleteEventForm, GetEventsForm
from .forms import MyMeetsForm, CreateProfileForm

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

'''
Purpose : This view is for logging in.
Returns : LoginForm if the user is yet to login.
Alternate : Redirects to Map view if the login is successfuly
'''
def login(request):
    loginFailed = False
    usernameMissing = False
    passwordMissing = False
    invalidData = False

    loginForm = LoginForm()

    if request.method == 'POST':
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():
            username = loginForm.cleaned_data['username']
            password = loginForm.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                auth_login(request,user)
                return HttpResponseRedirect('/map/')
            else:
                loginFailed = True
        else:
            if not loginForm.data['username']:
                usernameMissing = True
            if not loginForm.data['password']:
                passwordMissing = True
            if not usernameMissing and not passwordMissing:
                invalidData = True

    data = {
        'form':loginForm,
        'loginFailed':loginFailed,
        'usernameMissing':usernameMissing,
        'passwordMissing':passwordMissing,
        'invalidData':invalidData
    }

    return render(request, 'mainapp/login.html', data)

'''
Purpose : This view is for signup
Returns : Signup form if the user is yet to signup
Alternate : If signup is successful then the user can redirect to create profile page
'''
def signup(request):
    registerSuccess = False
    registerFailed = False
    usernameMissing = False
    usernameExists = False
    passwordMissing = False
    emailMissing = False
    passwordsDontMatch = False
    passwordTooShort = False
    invalidData = False

    registerForm = RegisterForm()

    if request.method == 'POST':
        registerForm = RegisterForm(request.POST)
        if registerForm.is_valid():
            username = registerForm.cleaned_data['username']
            password1 = registerForm.cleaned_data['password1']
            password2 = registerForm.cleaned_data['password2']
            email = registerForm.cleaned_data['email']
            # Passwords must match
            if password1 == password2:
                # Password must have a minimum length
                if len(password1) > 5:
                    if not User.objects.filter(username=username).exists():
                        try:
                            newUser = User.objects.create_user(username, email, password1)
                            newUser.save()
                            newUserProfile = UserProfile(user=newUser,username=username)
                            newUserProfile.save()
                        except:
                            registerFailed = True
                        else:
                            registerSuccess = True
                            authenticate(username=username,password=password1)
                    else:
                        usernameExists = True
                else:
                    passwordTooShort = True
            else:
                passwordsDontMatch = True
        else:
            if not registerForm.data['username']:
                usernameMissing = True
            if not registerForm.data['password1']:
                passwordMissing = True
            if not registerForm.data['email']:
                emailMissing = True
            if not usernameMissing and not passwordMissing and not emailMissing:
                invalidData = True

    data = {
        'form':registerForm,
        'registerSuccess':registerSuccess,
        'registerFailed':registerFailed,
        'usernameMissing':usernameMissing,
        'usernameExists':usernameExists,
        'passwordMissing':passwordMissing,
        'emailMissing':emailMissing,
        'passwordsDontMatch':passwordsDontMatch,
        'passwordTooShort': passwordTooShort,
        'invalidData':invalidData
    }

    return render(request, 'mainapp/signup.html', data)

'''
Purpose : This view is to create a profile.
Returns : A CreateProfileForm if they are yet to complete their profile.
Alternate : If profile creation is successful redirects to map page.
'''
def createprofile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')

    error = False
    invalid_data = False
    form = CreateProfileForm()

    if request.method == "POST":
        form = CreateProfileForm(request.POST, request.FILES)
        if form.is_valid():
            invalid_data = False
            try:
                description = form.cleaned_data['description']
                picture = form.cleaned_data['display_picture']
                interests = form.cleaned_data['interests']

                user_profile = UserProfile.objects.get(user=request.user)
                user_profile.description = description
                user_profile.display_picture = picture
                user_profile.save()
                user_profile.interests = interests
                user_profile.save()

                return HttpResponseRedirect('/map/')
            except:
                error = True
        else:
            print(form.errors)
            invalid_data = True

    data = {
        'error':error,
        'invalid_data':invalid_data,
        'form':form
    }

    return render(request, 'mainapp/createProfile.html', data)

'''
Purpose : This view is to view and update the profile
Returns : ProfileForm
Alternate : None
'''
def profile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')

    current_user = UserProfile.objects.get(user=request.user)
    interests = Interest.objects.filter(userprofile=current_user)

    data = {
        'profile':current_user,
        'interests':interests
    }

    return render(request, 'mainapp/profile.html', data)

'''
Purpose : This view is to see the map
Returns : CreateEventForm to create a new event by clicking on the map
Alternate : Redirects to login if user is not authenticated
'''
def map(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')

    eventForm = CreateEventForm()

    data = {
        'event_form':eventForm,
    }

    return render(request,'mainapp/map.html',data)

'''
Purpose : This view is to see their meets
Returns : A list of their meets
Alternate : Redirects to login if user is not authenticated
'''
def mymeets(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')

    current_user = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        form = MyMeetsForm(request.POST)
        form.is_valid()
        action_type = form.cleaned_data['action_type']
        meet_id = form.cleaned_data['event_id']
        meet = Event.objects.get(pk=meet_id)
        if action_type == "delete":
            meet.delete()
        else:
            current_user.events.remove(meet)
            current_user.save()

    joined_events = Event.objects.filter(
                                userprofile=current_user
                                ).exclude(
                                creator=current_user
                                )
    created_events = Event.objects.filter(creator=current_user)

    data = {
        'joined':joined_events,
        'created':created_events
    }

    return render(request, 'mainapp/mymeets.html', data)

'''
REST Endpoints start here
'''

'''
Purpose : Get the details required by the map page
'''
@api_view(['GET'])
def get_user_details(request):
    success = False

    try:
        current_user = UserProfile.objects.get(user=request.user)

        # Get all of the events of this user, minus the ones they created
        events = Event.objects.filter(
                            userprofile=current_user
                            )
        events_json = serializers.serialize("json", events, use_natural_foreign_keys=True,
                                            use_natural_primary_keys=True)

        # Get the users interests
        interests = Interest.objects.filter(userprofile=current_user)
        interests_json = serializers.serialize("json", interests,
                                                use_natural_foreign_keys=True,
                                                use_natural_primary_keys=True)

        # Get ALL interests
        all_interests = Interest.objects.all()
        all_interests_json = serializers.serialize("json", all_interests,
                                                    use_natural_foreign_keys=True,
                                                    use_natural_primary_keys=True)

        success = True
    except:
        success = False

    response = {
        'username':current_user.username,
        'events':events_json,
        'interests':interests_json,
        'all_interests':all_interests_json
    }

    if success:
        return Response(response, status=status.HTTP_200_OK)
    else:
        return Response(response, status=status.HTTP_400_BAD_REQUEST)

'''
Purpose : User creates an event.
'''

MeetMap/mainapp/templates/mainapp/createProfile.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static '/mainapp/css/createProfile.css' %}" rel="stylesheet">
    <script src="{% static '/mainapp/jquery/jquery.js' %}"></script>
    <script src="{% static '/mainapp/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static '/mainapp/js/createProfile.js' %}"></script>
    <title>MeetMap</title>
  </head>

  <body>
    <div class="container-fluid vertical-center">
      <div class="profileform">
        <form action="/createprofile/" method="post"
              enctype="multipart/form-data" >
          {% csrf_token %}
          <h1 class="header text-center">MeetMap</h1>
          <h2 class="text-center">Update Your Profile</h2>
          <div class="form-group">
            <label for="id_{{ form.description.name }}">
              {{ form.description.label }}
            </label>
            <textarea type="text" class="form-control description"
              id="id_{{ form.description.name }}"
              name="{{ form.description.name }}"
              value="{{ form.description.value|default_if_none:"" }}">
            </textarea>
          </div>
          <div class="form-group">
            <label for="id_{{ form.display_picture.name }}">
              {{ form.display_picture.label }}
            </label>
            <br>
            {{ form.display_picture }}
          </div>
          <div class="form-group">
            <label for="id_{{ form.interests.name }}">
              {{ form.interests.label }}
            </label>
            <br>
            {{ form.interests }}
          </div>

          {% if error %}
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Dismiss">
              <span aria-hidden="true">
                &times;
              </span>
            </button>
            <strong>Error !</strong> Something went wrong saving your profile.
          </div>
          {% endif %}

          {% if invalid_data %}
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Dismiss">
              <span aria-hidden="true">
                &times;
              </span>
            </button>
            <strong>Missing !</strong> You need to enter all the information.
          </div>
          {% endif %}

          <button id="saveButton" type="submit" class="btn btn-primary button">
            Save and Continue
          </button>
        </form>
      </div>
    </div>
  </body>

</html>

MeetMap/mainapp/templates/mainapp/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "/mainapp/css/login.css" %}" rel="stylesheet">
    <script src="{% static "/mainapp/jquery/jquery.js" %}"></script>
    <script src="{% static "/mainapp/bootstrap/js/bootstrap.js" %}"></script>
    <script src="{% static "/mainapp/js/login.js" %}"></script>
    <title>MeetMap</title>
  </head>

  <body>
    <div class="container-fluid vertical-center">
      <div class="loginform">
        <form action="/" method="post">
          {% csrf_token %}
          <h1 class="header text-center">MeetMap</h1>
          <div class="form-group">
            <label for="id_{{ form.username.name }}">{{ form.username.label }}</label>
            <input type="username" class="form-control"
              id="id_{{ form.username.name }}"
              name="{{ form.username.name }}"
              value="{{ form.username.value|default_if_none:"" }}"
              placeholder="Username">
          </div>
          <div class="form-group">
            <label for="id_{{ form.password.name }}">{{ form.password.label }}</label>
            <input type="password" class="form-control"
              id="id_{{ form.password.name }}"
              name="{{ form.password.name }}"
              value="{{ form.password.value|default_if_none:"" }}"
              placeholder="Password">
          </div>

          {% if loginFailed %}
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Dismiss">
              <span aria-hidden="true">
                &times;
              </span>
            </button>
            <strong>Login Failed!</strong> Invalid username or password
          </div>
          {% endif %}

          {% if usernameMissing %}
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Dismiss">
              <span aria-hidden="true">
                &times;
              </span>
            </button>
            <strong>Login Failed!</strong> Username is required but missing
          </div>
          {% endif %}

          {% if passwordMissing %}
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Dismiss">
              <span aria-hidden="true">
                &times;
              </span>
            </button>
            <strong>Login Failed!</strong> Password is required but missing
          </div>
          {% endif %}

          {% if invalidData %}
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Dismiss">
              <span aria-hidden="true">
                &times;
              </span>
            </button>
            <strong>Invalid Data!</strong>
            You must enter letters, numbers or special characters
          </div>
          {% endif %}

          <button id="loginButton" type="submit" class="btn btn-primary button">
            Login
          </button>
        </form>
        <a href="{% url 'mainapp:signup' %}" type="button" class="btn btn-link button">
          Don't have an account ? Register here!!!
        </a>
      </div>
    </div>
  </body>

</html>

MeetMap/mainapp/templates/mainapp/main.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static "/mainapp/jquery/jquery.js" %}"></script>
    <script src="{% static "/mainapp/bootstrap/js/bootstrap.js" %}"></script>
    <script src="{% static "/mainapp/js/sidebar.js" %}"></script>
    <link href="{% static "/mainapp/css/sidebar.css" %}" rel="stylesheet">
    <title>MeetMap</title>
    {% block head %}
    {% endblock %}
</head>

<body>
  <div class="sidebar-nav">
    <ul class="sidebar-list">
      <li class="sidebar-brand">
          <h1 class="header">MeetMap</h1>
      </li>
      <li>
          <h4 style="color: #28a4c9;">{{ user.username }}</h4>
      </li>
      <li>
          <a href="{% url 'mainapp:profile' %}">Profile</a>
      </li>
      <li>
          <a href="{% url 'mainapp:map' %}">Map</a>
      </li>
      <li>
          <a href="{% url 'mainapp:mymeets' %}">My Meets</a>
      </li>
      <li>
          <a href="{% url 'mainapp:login' %}">Logout</a>
      </li>
    </ul>
  </div>
  <div class="main-content">
    {% block content %}
    {% endblock %}
  </div>
    {% block scripts %}
    {% endblock %}
</body>

{% block dialogs %}
{% endblock %}

</html>

MeetMap/mainapp/templates/mainapp/mymeets.html
{% extends 'mainapp/main.html' %}
{% load static %}

{% block head %}
    <link href="{% static "/mainapp/css/mymeets.css" %}" rel="stylesheet">
    <script src="{% static "/mainapp/js/mymeets.js" %}"></script>
{% endblock %}

{% block content %}
<div class="meets">
  <div id="created-meets-section">
    <button class="btn btn-link" id="created-meets-button">
      <h3><u>Hide meets i created</u></h3>
    </button>
    <hr>
    <div id="created-meets">
      {% if created %}
        <ul>
          {% for event in created %}
            <li>
              <form action="/mymeets/" method="post">
                {% csrf_token %}
                <div class="form-group hidden">
                  <label for="id_event_id">id : </label>
                  <input type="number" class="form-control" id="id_event_id"
                    name="event_id" value="{{ event.pk }}">
                </div>
                <div class="form-group hidden">
                  <label for="id_action_type">type : </label>
                  <input type="text" class="form-control" id="id_action_type"
                    name="action_type" value="delete">
                </div>
                <div class="form-group">
                  <label for="name">Name : </label>
                  <label id="name">{{ event.name }}</label>
                </div>
                <div class="form-group">
                  <label for="name">Name : </label>
                  <label id="name">{{ event.name }}</label>
                </div>
                <div class="form-group">
                  <label for="from">From : </label>
                  <label id="from">{{ event.from_time }}</label>
                </div>
                <div class="form-group">
                  <label for="to">To : </label>
                  <label id="to">{{ event.to_time }}</label>
                </div>
                <div class="form-group">
                  <label for="location">Location : </label>
                  <label id="location">{{ event.location }}</label>
                </div>
                <div class="form-group">
                  <label for="description">Description : </label>
                  <label id="description" class="description">
                    {{ event.description }}
                  </label>
                </div>
                <button id="deleteButton" type="submit" class="btn btn-danger button">
                  Delete
                </button>
              </form>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <h4>You have created 0 meets</h4>
      {% endif %}
    </div>
  </div>
  <div id="joined-meets-section">
    <button class="btn btn-link" id="joined-meets-button">
      <h3><u>Hide meets i joined</u></h3>
    </button>
    <hr>
    <div id="joined-meets">
      {% if joined %}
        <ul>
          {% for event in joined %}
            <li>
              <form action="/mymeets/" method="post">
                {% csrf_token %}
                <div class="form-group hidden">
                  <label for="id_event_id">id : </label>
                  <input type="number" class="form-control" id="id_event_id"
                    name="event_id" value="{{ event.pk }}">
                </div>
                <div class="form-group hidden">
                  <label for="id_action_type">type : </label>
                  <input type="text" class="form-control" id="id_action_type"
                    name="action_type" value="cancel">
                </div>
                <div class="form-group">
                  <label for="name">Name : </label>
                  <label id="name">{{ event.name }}</label>
                </div>
                <div class="form-group">
                  <label for="name">Name : </label>
                  <label id="name">{{ event.name }}</label>
                </div>
                <div class="form-group">
                  <label for="from">From : </label>
                  <label id="from">{{ event.from_time }}</label>
                </div>
                <div class="form-group">
                  <label for="to">To : </label>
                  <label id="to">{{ event.to_time }}</label>
                </div>
                <div class="form-group">
                  <label for="location">Location : </label>
                  <label id="location">{{ event.location }}</label>
                </div>
                <div class="form-group">
                  <label for="description">Description : </label>
                  <label id="description" class="description">
                    {{ event.description }}
                  </label>
                </div>
                <button id="cancelButton" type="submit" class="btn btn-primary button">
                  I'm not going
                </button>
              </form>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <h4>You have joined 0 meets</h4>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

MeetMap/mainapp/templates/mainapp/profile.html
{% extends 'mainapp/main.html' %}

{% load static %}

{% block head %}
    <script src="{% static '/mainapp/js/profile.js' %} "></script>
    <link href="{% static '/mainapp/css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content%}
 <div class="container display top-margin">
     <div class="profile">
       <h5><b>Username:</b> {{ profile.username }}</h5>
       <h5><b>Description:</b> {{ profile.description }}</h5>
       <h5><b>Interests:</b></h5>
       {% for interest in interests %}
       {{ interest }}
       <br>
       {% endfor %}
       <br>
       <a href="{% url 'mainapp:createprofile' %}">
           <button>Edit Profile</button>
       </a>
     </div>
</div>
{% endblock %}